import React from 'react'
import './globals.css'
import '@radix-ui/themes/styles.css'
import '../theme.config.css'
import { Theme, ThemePanel } from '@radix-ui/themes'
import { Lato } from 'next/font/google'

import localFont from 'next/font/local'
import { cn } from '@/lib/utils'

const ligConsolata = localFont({
	src: [
		{
			path: '../static/fonts/Ligconsolata-Regular.woff',
			weight: '400',
			style: 'normal',
		},
		{
			path: '../static/fonts/Ligconsolata-Bold.woff',
			weight: '700',
			style: 'normal',
		},
	],
	variable: '--font-lig-consolata',
})

const lato = Lato({
	subsets: ['latin'],
	weight: ['100', '300', '400', '700', '900'],
	variable: '--font-lato',
})

export const metadata = {
	title: 'Hi, I am Kyle',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en" className={cn(ligConsolata.variable, lato.variable)}>
			<body className="text-brand-white">
				<Theme>
					{children}
					{/* <ThemePanel /> */}
				</Theme>
			</body>
		</html>
	)
}
